#!/bin/sh
BASEDIR=$(dirname $0)
cd $BASEDIR
cd ..

# Build the dissertation.
xelatex dissertation
bibtex dissertation
xelatex dissertation
xelatex dissertation

cp *.pdf publish/
rm *.pdf

git clean -d  -fx -f
